// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"net/netip"

	uuid "github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type CheckResult struct {
	ID               uuid.UUID          `json:"id"`
	MonitorID        uuid.UUID          `json:"monitor_id"`
	StartedAt        pgtype.Timestamptz `json:"started_at"`
	FinishedAt       pgtype.Timestamptz `json:"finished_at"`
	DurationMs       int64              `json:"duration_ms"`
	Outcome          string             `json:"outcome"`
	StatusCode       pgtype.Int2        `json:"status_code"`
	ErrorCode        pgtype.Text        `json:"error_code"`
	ErrorDescription pgtype.Text        `json:"error_description"`
	DialedIp         *netip.Addr        `json:"dialed_ip"`
	TlsExpiresAt     pgtype.Timestamptz `json:"tls_expires_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

type Monitor struct {
	ID                uuid.UUID          `json:"id"`
	Name              string             `json:"name"`
	Slug              string             `json:"slug"`
	Description       pgtype.Text        `json:"description"`
	Kind              string             `json:"kind"`
	Url               string             `json:"url"`
	HttpMethod        string             `json:"http_method"`
	ExpectedStatusMin int16              `json:"expected_status_min"`
	ExpectedStatusMax int16              `json:"expected_status_max"`
	IntervalSeconds   int32              `json:"interval_seconds"`
	TimeoutMs         int32              `json:"timeout_ms"`
	FailureThreshold  int16              `json:"failure_threshold"`
	RecoveryThreshold int16              `json:"recovery_threshold"`
	Enabled           bool               `json:"enabled"`
	Public            bool               `json:"public"`
	Version           int64              `json:"version"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	ArchivedAt        pgtype.Timestamptz `json:"archived_at"`
}

type MonitorState struct {
	MonitorID            uuid.UUID          `json:"monitor_id"`
	State                string             `json:"state"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
	LastCheckResultID    pgtype.UUID        `json:"last_check_result_id"`
	LastCheckedAt        pgtype.Timestamptz `json:"last_checked_at"`
	LastOutcome          pgtype.Text        `json:"last_outcome"`
	LastStatusCode       pgtype.Int2        `json:"last_status_code"`
	LastDurationMs       pgtype.Int8        `json:"last_duration_ms"`
	ConsecutiveFailures  int64              `json:"consecutive_failures"`
	ConsecutiveSuccesses int64              `json:"consecutive_successes"`
}
