// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	uuid "github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Monitor struct {
	ID                uuid.UUID          `json:"id"`
	Name              string             `json:"name"`
	Slug              string             `json:"slug"`
	Description       pgtype.Text        `json:"description"`
	Kind              string             `json:"kind"`
	Url               string             `json:"url"`
	HttpMethod        string             `json:"http_method"`
	ExpectedStatusMin int16              `json:"expected_status_min"`
	ExpectedStatusMax int16              `json:"expected_status_max"`
	IntervalSeconds   int32              `json:"interval_seconds"`
	TimeoutMs         int32              `json:"timeout_ms"`
	FailureThreshold  int16              `json:"failure_threshold"`
	RecoveryThreshold int16              `json:"recovery_threshold"`
	Enabled           bool               `json:"enabled"`
	Public            bool               `json:"public"`
	Version           int64              `json:"version"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type MonitorState struct {
	MonitorID uuid.UUID          `json:"monitor_id"`
	State     string             `json:"state"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}
