// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: monitors.sql

package db

import (
	"context"

	uuid "github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const archiveMonitor = `-- name: ArchiveMonitor :one
UPDATE monitors SET
    enabled = false,
    public = false,
    archived_at = now(),
    next_check_at = NULL,
    updated_at = now(),
    version = version + 1
WHERE id = $1 AND archived_at IS NULL
RETURNING id
`

func (q *Queries) ArchiveMonitor(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, archiveMonitor, id)
	var id_2 uuid.UUID
	err := row.Scan(&id_2)
	return id_2, err
}

const createMonitor = `-- name: CreateMonitor :one
INSERT INTO monitors (
    id, name, slug, description, kind, url, http_method,
    expected_status_min, expected_status_max, interval_seconds, timeout_ms,
    failure_threshold, recovery_threshold, enabled, public, next_check_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7,
    $8, $9, $10, $11, $12, $13, $14, $15, CASE WHEN $14 THEN transaction_timestamp() ELSE NULL END
)
RETURNING id, name, slug, description, kind, url, http_method, expected_status_min, expected_status_max, interval_seconds, timeout_ms, failure_threshold, recovery_threshold, enabled, public, version, created_at, updated_at, archived_at, next_check_at
`

type CreateMonitorParams struct {
	ID                uuid.UUID   `json:"id"`
	Name              string      `json:"name"`
	Slug              string      `json:"slug"`
	Description       pgtype.Text `json:"description"`
	Kind              string      `json:"kind"`
	Url               string      `json:"url"`
	HttpMethod        string      `json:"http_method"`
	ExpectedStatusMin int16       `json:"expected_status_min"`
	ExpectedStatusMax int16       `json:"expected_status_max"`
	IntervalSeconds   int32       `json:"interval_seconds"`
	TimeoutMs         int32       `json:"timeout_ms"`
	FailureThreshold  int16       `json:"failure_threshold"`
	RecoveryThreshold int16       `json:"recovery_threshold"`
	Enabled           bool        `json:"enabled"`
	Public            bool        `json:"public"`
}

func (q *Queries) CreateMonitor(ctx context.Context, arg CreateMonitorParams) (Monitor, error) {
	row := q.db.QueryRow(ctx, createMonitor,
		arg.ID,
		arg.Name,
		arg.Slug,
		arg.Description,
		arg.Kind,
		arg.Url,
		arg.HttpMethod,
		arg.ExpectedStatusMin,
		arg.ExpectedStatusMax,
		arg.IntervalSeconds,
		arg.TimeoutMs,
		arg.FailureThreshold,
		arg.RecoveryThreshold,
		arg.Enabled,
		arg.Public,
	)
	var i Monitor
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Kind,
		&i.Url,
		&i.HttpMethod,
		&i.ExpectedStatusMin,
		&i.ExpectedStatusMax,
		&i.IntervalSeconds,
		&i.TimeoutMs,
		&i.FailureThreshold,
		&i.RecoveryThreshold,
		&i.Enabled,
		&i.Public,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
		&i.NextCheckAt,
	)
	return i, err
}

const createMonitorState = `-- name: CreateMonitorState :one
INSERT INTO monitor_states (monitor_id, state)
VALUES ($1, $2)
RETURNING monitor_id, state, updated_at, last_check_result_id, last_checked_at, last_outcome, last_status_code, last_duration_ms, consecutive_failures, consecutive_successes, last_applied_scheduled_at
`

type CreateMonitorStateParams struct {
	MonitorID uuid.UUID `json:"monitor_id"`
	State     string    `json:"state"`
}

func (q *Queries) CreateMonitorState(ctx context.Context, arg CreateMonitorStateParams) (MonitorState, error) {
	row := q.db.QueryRow(ctx, createMonitorState, arg.MonitorID, arg.State)
	var i MonitorState
	err := row.Scan(
		&i.MonitorID,
		&i.State,
		&i.UpdatedAt,
		&i.LastCheckResultID,
		&i.LastCheckedAt,
		&i.LastOutcome,
		&i.LastStatusCode,
		&i.LastDurationMs,
		&i.ConsecutiveFailures,
		&i.ConsecutiveSuccesses,
		&i.LastAppliedScheduledAt,
	)
	return i, err
}

const getMonitor = `-- name: GetMonitor :one
SELECT
    m.id, m.name, m.slug, m.description, m.kind, m.url, m.http_method,
    m.expected_status_min, m.expected_status_max, m.interval_seconds,
    m.timeout_ms, m.failure_threshold, m.recovery_threshold, m.enabled,
    m.public, m.version, m.created_at, m.updated_at, m.archived_at,
    s.state, s.updated_at AS state_updated_at
FROM monitors m
JOIN monitor_states s ON s.monitor_id = m.id
WHERE m.id = $1
`

type GetMonitorRow struct {
	ID                uuid.UUID          `json:"id"`
	Name              string             `json:"name"`
	Slug              string             `json:"slug"`
	Description       pgtype.Text        `json:"description"`
	Kind              string             `json:"kind"`
	Url               string             `json:"url"`
	HttpMethod        string             `json:"http_method"`
	ExpectedStatusMin int16              `json:"expected_status_min"`
	ExpectedStatusMax int16              `json:"expected_status_max"`
	IntervalSeconds   int32              `json:"interval_seconds"`
	TimeoutMs         int32              `json:"timeout_ms"`
	FailureThreshold  int16              `json:"failure_threshold"`
	RecoveryThreshold int16              `json:"recovery_threshold"`
	Enabled           bool               `json:"enabled"`
	Public            bool               `json:"public"`
	Version           int64              `json:"version"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	ArchivedAt        pgtype.Timestamptz `json:"archived_at"`
	State             string             `json:"state"`
	StateUpdatedAt    pgtype.Timestamptz `json:"state_updated_at"`
}

func (q *Queries) GetMonitor(ctx context.Context, id uuid.UUID) (GetMonitorRow, error) {
	row := q.db.QueryRow(ctx, getMonitor, id)
	var i GetMonitorRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Kind,
		&i.Url,
		&i.HttpMethod,
		&i.ExpectedStatusMin,
		&i.ExpectedStatusMax,
		&i.IntervalSeconds,
		&i.TimeoutMs,
		&i.FailureThreshold,
		&i.RecoveryThreshold,
		&i.Enabled,
		&i.Public,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
		&i.State,
		&i.StateUpdatedAt,
	)
	return i, err
}

const listMonitors = `-- name: ListMonitors :many
SELECT
    m.id, m.name, m.slug, m.description, m.kind, m.url, m.http_method,
    m.expected_status_min, m.expected_status_max, m.interval_seconds,
    m.timeout_ms, m.failure_threshold, m.recovery_threshold, m.enabled,
    m.public, m.version, m.created_at, m.updated_at, m.archived_at,
    s.state, s.updated_at AS state_updated_at
FROM monitors m
JOIN monitor_states s ON s.monitor_id = m.id
WHERE m.archived_at IS NULL
ORDER BY m.created_at DESC, m.id DESC
LIMIT $1 OFFSET $2
`

type ListMonitorsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListMonitorsRow struct {
	ID                uuid.UUID          `json:"id"`
	Name              string             `json:"name"`
	Slug              string             `json:"slug"`
	Description       pgtype.Text        `json:"description"`
	Kind              string             `json:"kind"`
	Url               string             `json:"url"`
	HttpMethod        string             `json:"http_method"`
	ExpectedStatusMin int16              `json:"expected_status_min"`
	ExpectedStatusMax int16              `json:"expected_status_max"`
	IntervalSeconds   int32              `json:"interval_seconds"`
	TimeoutMs         int32              `json:"timeout_ms"`
	FailureThreshold  int16              `json:"failure_threshold"`
	RecoveryThreshold int16              `json:"recovery_threshold"`
	Enabled           bool               `json:"enabled"`
	Public            bool               `json:"public"`
	Version           int64              `json:"version"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	ArchivedAt        pgtype.Timestamptz `json:"archived_at"`
	State             string             `json:"state"`
	StateUpdatedAt    pgtype.Timestamptz `json:"state_updated_at"`
}

func (q *Queries) ListMonitors(ctx context.Context, arg ListMonitorsParams) ([]ListMonitorsRow, error) {
	rows, err := q.db.Query(ctx, listMonitors, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMonitorsRow{}
	for rows.Next() {
		var i ListMonitorsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.Kind,
			&i.Url,
			&i.HttpMethod,
			&i.ExpectedStatusMin,
			&i.ExpectedStatusMax,
			&i.IntervalSeconds,
			&i.TimeoutMs,
			&i.FailureThreshold,
			&i.RecoveryThreshold,
			&i.Enabled,
			&i.Public,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ArchivedAt,
			&i.State,
			&i.StateUpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockMonitor = `-- name: LockMonitor :one
SELECT id, archived_at FROM monitors WHERE id = $1 FOR UPDATE
`

type LockMonitorRow struct {
	ID         uuid.UUID          `json:"id"`
	ArchivedAt pgtype.Timestamptz `json:"archived_at"`
}

func (q *Queries) LockMonitor(ctx context.Context, id uuid.UUID) (LockMonitorRow, error) {
	row := q.db.QueryRow(ctx, lockMonitor, id)
	var i LockMonitorRow
	err := row.Scan(&i.ID, &i.ArchivedAt)
	return i, err
}

const setMonitorEnabled = `-- name: SetMonitorEnabled :one
UPDATE monitors SET
    enabled = $2,
    next_check_at = CASE WHEN $2 THEN transaction_timestamp() ELSE NULL END,
    updated_at = now(),
    version = version + 1
WHERE id = $1
RETURNING id, name, slug, description, kind, url, http_method, expected_status_min, expected_status_max, interval_seconds, timeout_ms, failure_threshold, recovery_threshold, enabled, public, version, created_at, updated_at, archived_at, next_check_at
`

type SetMonitorEnabledParams struct {
	ID      uuid.UUID `json:"id"`
	Enabled bool      `json:"enabled"`
}

func (q *Queries) SetMonitorEnabled(ctx context.Context, arg SetMonitorEnabledParams) (Monitor, error) {
	row := q.db.QueryRow(ctx, setMonitorEnabled, arg.ID, arg.Enabled)
	var i Monitor
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Kind,
		&i.Url,
		&i.HttpMethod,
		&i.ExpectedStatusMin,
		&i.ExpectedStatusMax,
		&i.IntervalSeconds,
		&i.TimeoutMs,
		&i.FailureThreshold,
		&i.RecoveryThreshold,
		&i.Enabled,
		&i.Public,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
		&i.NextCheckAt,
	)
	return i, err
}

const setMonitorState = `-- name: SetMonitorState :one
UPDATE monitor_states SET
    state = $2::varchar,
    consecutive_failures = CASE WHEN $2::varchar = 'pending' THEN 0 ELSE consecutive_failures END,
    consecutive_successes = CASE WHEN $2::varchar = 'pending' THEN 0 ELSE consecutive_successes END,
    updated_at = now()
WHERE monitor_id = $1
RETURNING monitor_id, state, updated_at, last_check_result_id, last_checked_at, last_outcome, last_status_code, last_duration_ms, consecutive_failures, consecutive_successes, last_applied_scheduled_at
`

type SetMonitorStateParams struct {
	MonitorID uuid.UUID `json:"monitor_id"`
	State     string    `json:"state"`
}

func (q *Queries) SetMonitorState(ctx context.Context, arg SetMonitorStateParams) (MonitorState, error) {
	row := q.db.QueryRow(ctx, setMonitorState, arg.MonitorID, arg.State)
	var i MonitorState
	err := row.Scan(
		&i.MonitorID,
		&i.State,
		&i.UpdatedAt,
		&i.LastCheckResultID,
		&i.LastCheckedAt,
		&i.LastOutcome,
		&i.LastStatusCode,
		&i.LastDurationMs,
		&i.ConsecutiveFailures,
		&i.ConsecutiveSuccesses,
		&i.LastAppliedScheduledAt,
	)
	return i, err
}

const updateMonitor = `-- name: UpdateMonitor :one
UPDATE monitors SET
    name = $2,
    slug = $3,
    description = $4,
    url = $5,
    http_method = $6,
    expected_status_min = $7,
    expected_status_max = $8,
    interval_seconds = $9,
    timeout_ms = $10,
    failure_threshold = $11,
    recovery_threshold = $12,
    public = $13,
    updated_at = now(),
    version = version + 1
WHERE id = $1 AND version = $14 AND archived_at IS NULL
RETURNING id, name, slug, description, kind, url, http_method, expected_status_min, expected_status_max, interval_seconds, timeout_ms, failure_threshold, recovery_threshold, enabled, public, version, created_at, updated_at, archived_at, next_check_at
`

type UpdateMonitorParams struct {
	ID                uuid.UUID   `json:"id"`
	Name              string      `json:"name"`
	Slug              string      `json:"slug"`
	Description       pgtype.Text `json:"description"`
	Url               string      `json:"url"`
	HttpMethod        string      `json:"http_method"`
	ExpectedStatusMin int16       `json:"expected_status_min"`
	ExpectedStatusMax int16       `json:"expected_status_max"`
	IntervalSeconds   int32       `json:"interval_seconds"`
	TimeoutMs         int32       `json:"timeout_ms"`
	FailureThreshold  int16       `json:"failure_threshold"`
	RecoveryThreshold int16       `json:"recovery_threshold"`
	Public            bool        `json:"public"`
	Version           int64       `json:"version"`
}

func (q *Queries) UpdateMonitor(ctx context.Context, arg UpdateMonitorParams) (Monitor, error) {
	row := q.db.QueryRow(ctx, updateMonitor,
		arg.ID,
		arg.Name,
		arg.Slug,
		arg.Description,
		arg.Url,
		arg.HttpMethod,
		arg.ExpectedStatusMin,
		arg.ExpectedStatusMax,
		arg.IntervalSeconds,
		arg.TimeoutMs,
		arg.FailureThreshold,
		arg.RecoveryThreshold,
		arg.Public,
		arg.Version,
	)
	var i Monitor
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Kind,
		&i.Url,
		&i.HttpMethod,
		&i.ExpectedStatusMin,
		&i.ExpectedStatusMax,
		&i.IntervalSeconds,
		&i.TimeoutMs,
		&i.FailureThreshold,
		&i.RecoveryThreshold,
		&i.Enabled,
		&i.Public,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
		&i.NextCheckAt,
	)
	return i, err
}
