// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: public_status.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listPublicStatus = `-- name: ListPublicStatus :many
WITH published AS (
    SELECT m.id, m.name, s.state, s.last_checked_at
    FROM monitors AS m
    JOIN monitor_states AS s ON s.monitor_id = m.id
    WHERE m.public = true AND m.archived_at IS NULL
    ORDER BY m.name
    LIMIT 100
)
SELECT p.name, p.state, p.last_checked_at,
       stats.checks_24h, stats.successes_24h
FROM published AS p
CROSS JOIN LATERAL (
    SELECT count(*)::bigint AS checks_24h,
           count(*) FILTER (WHERE r.outcome = 'success')::bigint AS successes_24h
    FROM check_results AS r
    WHERE r.monitor_id = p.id
      AND r.finished_at >= transaction_timestamp() - interval '24 hours'
) AS stats
ORDER BY p.name
`

type ListPublicStatusRow struct {
	Name          string             `json:"name"`
	State         string             `json:"state"`
	LastCheckedAt pgtype.Timestamptz `json:"last_checked_at"`
	Checks24h     int64              `json:"checks_24h"`
	Successes24h  int64              `json:"successes_24h"`
}

func (q *Queries) ListPublicStatus(ctx context.Context) ([]ListPublicStatusRow, error) {
	rows, err := q.db.Query(ctx, listPublicStatus)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPublicStatusRow{}
	for rows.Next() {
		var i ListPublicStatusRow
		if err := rows.Scan(
			&i.Name,
			&i.State,
			&i.LastCheckedAt,
			&i.Checks24h,
			&i.Successes24h,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
