// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: retention.sql

package db

import (
	"context"

	uuid "github.com/google/uuid"
)

const deleteExpiredCheckResults = `-- name: DeleteExpiredCheckResults :many
WITH expired AS (
    SELECT id FROM check_results
    WHERE started_at < transaction_timestamp() - make_interval(days => $1::integer)
    ORDER BY started_at, id
    LIMIT $2::integer
    FOR UPDATE SKIP LOCKED
)
DELETE FROM check_results AS results
USING expired
WHERE results.id = expired.id
RETURNING results.id
`

type DeleteExpiredCheckResultsParams struct {
	RetentionDays int32 `json:"retention_days"`
	BatchSize     int32 `json:"batch_size"`
}

func (q *Queries) DeleteExpiredCheckResults(ctx context.Context, arg DeleteExpiredCheckResultsParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, deleteExpiredCheckResults, arg.RetentionDays, arg.BatchSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteExpiredCompletedExecutions = `-- name: DeleteExpiredCompletedExecutions :many
WITH expired AS (
    SELECT executions.id FROM scheduled_executions AS executions
    WHERE executions.scheduled_at < transaction_timestamp() - make_interval(days => $1::integer)
      AND executions.status IN ('completed', 'skipped')
      AND NOT EXISTS (SELECT 1 FROM check_results AS results WHERE results.execution_id = executions.id)
    ORDER BY executions.scheduled_at, executions.id
    LIMIT $2::integer
    FOR UPDATE OF executions SKIP LOCKED
)
DELETE FROM scheduled_executions AS executions
USING expired
WHERE executions.id = expired.id
RETURNING executions.id
`

type DeleteExpiredCompletedExecutionsParams struct {
	RetentionDays int32 `json:"retention_days"`
	BatchSize     int32 `json:"batch_size"`
}

func (q *Queries) DeleteExpiredCompletedExecutions(ctx context.Context, arg DeleteExpiredCompletedExecutionsParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, deleteExpiredCompletedExecutions, arg.RetentionDays, arg.BatchSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
