// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: scheduler.sql

package db

import (
	"context"

	uuid "github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const advanceMonitorSchedule = `-- name: AdvanceMonitorSchedule :exec
UPDATE monitors
SET next_check_at = next_check_at + (
        (floor(extract(epoch FROM (transaction_timestamp() - next_check_at)) / interval_seconds) + 1)
        * interval_seconds * interval '1 second'
    ),
    updated_at = now()
WHERE id = $1
`

func (q *Queries) AdvanceMonitorSchedule(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, advanceMonitorSchedule, id)
	return err
}

const canStartScheduledExecution = `-- name: CanStartScheduledExecution :one
SELECT EXISTS(
    SELECT 1
    FROM scheduled_executions
    WHERE id = $1
      AND status = 'claimed'
      AND lease_owner = $2
      AND lease_expires_at >= transaction_timestamp() + ($3::double precision * interval '1 second')
)
`

type CanStartScheduledExecutionParams struct {
	ExecutionID     uuid.UUID   `json:"execution_id"`
	LeaseOwner      pgtype.UUID `json:"lease_owner"`
	RequiredSeconds float64     `json:"required_seconds"`
}

func (q *Queries) CanStartScheduledExecution(ctx context.Context, arg CanStartScheduledExecutionParams) (bool, error) {
	row := q.db.QueryRow(ctx, canStartScheduledExecution, arg.ExecutionID, arg.LeaseOwner, arg.RequiredSeconds)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const claimAvailableExecutions = `-- name: ClaimAvailableExecutions :many
WITH claimable AS (
    SELECT e.id
    FROM scheduled_executions e
    JOIN monitors m ON m.id = e.monitor_id
    WHERE m.enabled
      AND m.archived_at IS NULL
      AND e.scheduled_at <= transaction_timestamp()
      AND (
          e.status = 'pending' OR
          (e.status = 'claimed' AND e.lease_expires_at <= transaction_timestamp())
      )
    ORDER BY e.scheduled_at, e.id
    FOR UPDATE OF e SKIP LOCKED
    LIMIT $3
)
UPDATE scheduled_executions e
SET status = 'claimed',
    lease_owner = $1,
    lease_expires_at = transaction_timestamp() + ($2::double precision * interval '1 second'),
    claim_count = e.claim_count + 1,
    updated_at = now()
FROM claimable
WHERE e.id = claimable.id
RETURNING e.id, e.monitor_id, e.scheduled_at, e.status, e.lease_owner, e.lease_expires_at, e.claim_count, e.finished_at, e.created_at, e.updated_at
`

type ClaimAvailableExecutionsParams struct {
	LeaseOwner   pgtype.UUID `json:"lease_owner"`
	LeaseSeconds float64     `json:"lease_seconds"`
	BatchSize    int32       `json:"batch_size"`
}

func (q *Queries) ClaimAvailableExecutions(ctx context.Context, arg ClaimAvailableExecutionsParams) ([]ScheduledExecution, error) {
	rows, err := q.db.Query(ctx, claimAvailableExecutions, arg.LeaseOwner, arg.LeaseSeconds, arg.BatchSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ScheduledExecution{}
	for rows.Next() {
		var i ScheduledExecution
		if err := rows.Scan(
			&i.ID,
			&i.MonitorID,
			&i.ScheduledAt,
			&i.Status,
			&i.LeaseOwner,
			&i.LeaseExpiresAt,
			&i.ClaimCount,
			&i.FinishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const completeScheduledExecution = `-- name: CompleteScheduledExecution :one
UPDATE scheduled_executions
SET status = 'completed', lease_owner = NULL, lease_expires_at = NULL,
    finished_at = transaction_timestamp(), updated_at = now()
WHERE id = $1
RETURNING id, monitor_id, scheduled_at, status, lease_owner, lease_expires_at, claim_count, finished_at, created_at, updated_at
`

func (q *Queries) CompleteScheduledExecution(ctx context.Context, id uuid.UUID) (ScheduledExecution, error) {
	row := q.db.QueryRow(ctx, completeScheduledExecution, id)
	var i ScheduledExecution
	err := row.Scan(
		&i.ID,
		&i.MonitorID,
		&i.ScheduledAt,
		&i.Status,
		&i.LeaseOwner,
		&i.LeaseExpiresAt,
		&i.ClaimCount,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getScheduledExecution = `-- name: GetScheduledExecution :one
SELECT id, monitor_id, scheduled_at, status, lease_owner, lease_expires_at, claim_count, finished_at, created_at, updated_at FROM scheduled_executions WHERE id = $1
`

func (q *Queries) GetScheduledExecution(ctx context.Context, id uuid.UUID) (ScheduledExecution, error) {
	row := q.db.QueryRow(ctx, getScheduledExecution, id)
	var i ScheduledExecution
	err := row.Scan(
		&i.ID,
		&i.MonitorID,
		&i.ScheduledAt,
		&i.Status,
		&i.LeaseOwner,
		&i.LeaseExpiresAt,
		&i.ClaimCount,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertScheduledExecution = `-- name: InsertScheduledExecution :one
INSERT INTO scheduled_executions (id, monitor_id, scheduled_at)
VALUES ($1, $2, $3)
ON CONFLICT (monitor_id, scheduled_at) DO NOTHING
RETURNING id, monitor_id, scheduled_at, status, lease_owner, lease_expires_at, claim_count, finished_at, created_at, updated_at
`

type InsertScheduledExecutionParams struct {
	ID          uuid.UUID          `json:"id"`
	MonitorID   uuid.UUID          `json:"monitor_id"`
	ScheduledAt pgtype.Timestamptz `json:"scheduled_at"`
}

func (q *Queries) InsertScheduledExecution(ctx context.Context, arg InsertScheduledExecutionParams) (ScheduledExecution, error) {
	row := q.db.QueryRow(ctx, insertScheduledExecution, arg.ID, arg.MonitorID, arg.ScheduledAt)
	var i ScheduledExecution
	err := row.Scan(
		&i.ID,
		&i.MonitorID,
		&i.ScheduledAt,
		&i.Status,
		&i.LeaseOwner,
		&i.LeaseExpiresAt,
		&i.ClaimCount,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const lockDueMonitors = `-- name: LockDueMonitors :many
SELECT id, next_check_at, interval_seconds, now() AS database_now
FROM monitors
WHERE enabled
  AND archived_at IS NULL
  AND next_check_at IS NOT NULL
  AND next_check_at <= transaction_timestamp()
ORDER BY next_check_at, id
FOR UPDATE SKIP LOCKED
LIMIT $1
`

type LockDueMonitorsRow struct {
	ID              uuid.UUID          `json:"id"`
	NextCheckAt     pgtype.Timestamptz `json:"next_check_at"`
	IntervalSeconds int32              `json:"interval_seconds"`
	DatabaseNow     interface{}        `json:"database_now"`
}

func (q *Queries) LockDueMonitors(ctx context.Context, batchSize int32) ([]LockDueMonitorsRow, error) {
	rows, err := q.db.Query(ctx, lockDueMonitors, batchSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LockDueMonitorsRow{}
	for rows.Next() {
		var i LockDueMonitorsRow
		if err := rows.Scan(
			&i.ID,
			&i.NextCheckAt,
			&i.IntervalSeconds,
			&i.DatabaseNow,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockScheduledExecution = `-- name: LockScheduledExecution :one
SELECT id, monitor_id, scheduled_at, status, lease_owner, lease_expires_at, claim_count, finished_at, created_at, updated_at FROM scheduled_executions WHERE id = $1 FOR UPDATE
`

func (q *Queries) LockScheduledExecution(ctx context.Context, id uuid.UUID) (ScheduledExecution, error) {
	row := q.db.QueryRow(ctx, lockScheduledExecution, id)
	var i ScheduledExecution
	err := row.Scan(
		&i.ID,
		&i.MonitorID,
		&i.ScheduledAt,
		&i.Status,
		&i.LeaseOwner,
		&i.LeaseExpiresAt,
		&i.ClaimCount,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const scheduledExecutionLeaseActive = `-- name: ScheduledExecutionLeaseActive :one
SELECT EXISTS(
    SELECT 1 FROM scheduled_executions
    WHERE id = $1 AND status = 'claimed' AND lease_expires_at > transaction_timestamp()
)
`

func (q *Queries) ScheduledExecutionLeaseActive(ctx context.Context, id uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, scheduledExecutionLeaseActive, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const skipPendingExecutions = `-- name: SkipPendingExecutions :exec
UPDATE scheduled_executions
SET status = 'skipped', finished_at = transaction_timestamp(), updated_at = now()
WHERE monitor_id = $1 AND status = 'pending'
`

func (q *Queries) SkipPendingExecutions(ctx context.Context, monitorID uuid.UUID) error {
	_, err := q.db.Exec(ctx, skipPendingExecutions, monitorID)
	return err
}
